name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clear Nx cache
        run: npx nx reset
        
      - name: Lint affected projects
        run: npx nx affected --target=lint --base=origin/main --head=HEAD --parallel=3
        timeout-minutes: 5

      - name: Test affected projects  
        run: npx nx affected --target=test --base=origin/main --head=HEAD --parallel=3 -- --watchAll=false --passWithNoTests

      - name: Type check affected projects
        run: npx nx affected --target=typecheck --base=origin/main --head=HEAD --parallel=3

  build-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build affected projects
        env:
          CI: true
        run: |
          npx nx affected --target=build --base=origin/main --head=HEAD --parallel=3 --skip-nx-cache
          echo "Build command completed with exit code: $?"
        timeout-minutes: 10

      - name: Check affected build outputs
        run: |
          # Get list of affected projects
          affected_projects=$(npx nx show projects --affected --base=origin/main --head=HEAD --type=app | tr '\n' ' ')
          
          if [ -z "$affected_projects" ]; then
            echo "✅ No affected applications to verify"
            exit 0
          fi
          
          for app in $affected_projects; do
            if [[ "$app" == *"pwa"* ]]; then
              if [ ! -d "dist/apps/$app" ]; then
                echo "❌ Build output directory not found for $app"
                exit 1
              fi
              
              if [ ! -f "dist/apps/$app/index.html" ]; then
                echo "❌ index.html not found in build output for $app"
                exit 1
              fi
              
              echo "✅ Build output verification passed for $app"
            fi
          done

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=high

      - name: Check for outdated dependencies
        run: npm outdated || true